apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.state.claimName }}
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.state.storageSize }}
  storageClassName: {{ .Values.state.storageClassName }}
