apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fileServer.service.name }}
  namespace: kube-system
spec:
  ports:
    - name: grpc
      port: {{ .Values.fileServer.service.port }}
      protocol: TCP
  selector:
    app: csi-synced-hostpath-controller
  type: ClusterIP
