controller:
  gomemlimit: "180MiB"
  livenessProbe:
    port: 27301
  resources:
    limits:
      cpu: 100m
      memory: 200Mi
    requests:
      cpu: 10m
      memory: 20Mi
driver:
  name: syncedhostpath.csi.k8s.io
fileServer:
  service:
    name: csi-synced-hostpath-fileserver
    port: 50051
logLevel: 2
networkPolicy:
  enabled: true
node:
  gomemlimit: "180MiB"
  livenessProbe:
    port: 27302
  resources:
    limits:
      cpu: 100m
      memory: 200Mi
    requests:
      cpu: 10m
      memory: 20Mi
pod:
  image: quay.io/touchardv/csi-driver-synced-hostpath
  imagePullPolicy: IfNotPresent
serviceAccountName: csi-synced-hostpath-controller-sa
state:
  claimName: csi-synced-hostpath
  storageSize: 10Gi
  storageClassName: hostpath
storageClass:
  name: synced-hostpath
  reclaimPolicy: Delete
