controller:
  livenessProbe:
    port: 27301
driver:
  name: syncedhostpath.csi.k8s.io
fileServer:
  service:
    name: csi-synced-hostpath-fileserver
    port: 50051
logLevel: 4
node:
  livenessProbe:
    port: 27302
pod:
  image: quay.io/touchardv/csi-driver-synced-hostpath:v0.0.3
serviceAccountName: csi-synced-hostpath-controller-sa
state:
  claimName: csi-synced-hostpath
  storageSize: 10Gi
  storageClassName: hostpath
storageClass:
  name: synced-hostpath
  reclaimPolicy: Delete
